#!/usr/bin/env bash
# verify-async-rwlock.sh -- E12-F AsyncRwLock TLA+ / TLC formal gate.
#
# Runs the correct E12 RwLock safety model and the negative/reachability
# models through TLC (audit #162 Phase 4):
#
#   E12RwLock (correct)                -> 13 named invariants PASS
#   E12RwLockNegReaderBypass           -> NoReaderBarging FAILS (reader barging bug)
#   E12RwLockNegNoReconcile            -> InvNoStrandedGrantableHead FAILS
#   E12RwLockNegWriterRevoke           -> ReaderRevocationFree FAILS (MODEL-002
#                                         negative control; generated by
#                                         scripts/formal/gen-rwlock-neg-writer-revoke.py)
#   E12RwLockNegDeadlinePrecedence     -> InvResourceFirstDeadline FAILS
#                                         (MODEL-003 negative control; generated
#                                         by scripts/formal/gen-rwlock-neg-deadline-precedence.py)
#   7 reachability witnesses           -> each NoReach* FAILS (state genuinely
#                                         reachable: cancel/expire reader-prefix
#                                         merge, cancel/expire writer-refused,
#                                         writer-blocked contrast, and the two
#                                         MODEL-003 timed-admission halves)
#
# Freshness gate (fail-closed): BEFORE any TLC run, both generated negatives
# are checked byte-for-byte against what the current positive model would
# produce (--check mode of their generators). A committed negative that went
# stale after a positive-model edit fails the gate here instead of silently
# checking an old mutation.
#
# Source-safe: TLC runs in an isolated mktemp workspace.
#
# Usage:
#   scripts/formal/verify-async-rwlock.sh
#   TLA2TOOLS_JAR=/opt/tla2tools.jar scripts/formal/verify-async-rwlock.sh
#
# Exit status: 0 iff the freshness checks pass AND the correct model passes
# AND every negative/reachability model produces the counterexample named by
# its cfg.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
spec="$repo/spec/tla/e12_rwlock"
WORKERS="${TLC_WORKERS:-auto}"

# Resolve jar via shared helper (sets TLA2TOOLS_JAR).
source "$here/resolve-jar.sh"
JAR="$TLA2TOOLS_JAR"

if ! command -v java >/dev/null 2>&1; then
  echo "error: java not found on PATH" >&2
  exit 2
fi
if [ ! -d "$spec" ]; then
  echo "error: spec dir $spec missing" >&2
  exit 2
fi

outroot="$(mktemp -d -t sluice-formal.e12-rwlock.XXXXXX)"
cleanup() {
  if [[ -n "$outroot" ]] && [[ "$outroot" == *sluice-formal.e12-rwlock.* ]]; then
    rm -rf -- "$outroot"
  fi
}
trap cleanup EXIT

workdir="$outroot/work"
mkdir -p "$workdir"
cp "$spec"/*.tla "$spec"/*.cfg "$workdir/"
cd "$workdir"

run() {
  local model="$1" cfg="$2" outfile="$3"
  local metadir="$outroot/meta-$model"
  mkdir -p "$metadir"
  java -XX:+UseParallelGC -cp "$JAR" tlc2.TLC -nowarning \
       -config "$cfg" -cleanup -workers "$WORKERS" \
       -metadir "$metadir" "$model" >"$outfile" 2>&1
  return 0
}

tlc_launched() { grep -q '^Starting\.\.\.' "$1"; }
tlc_passed() { grep -q 'Model checking completed. No error has been found' "$1"; }
tlc_deadlocked() { grep -qiE '^(Error: )*Deadlock reached|is deadlocked' "$1"; }
named_violation() { grep -Eq "Invariant $2 is violated" "$1"; }
states_line() { grep -m1 'states generated' "$1" || true; }

expect_pass() {
  local label="$1" model="$2" cfg="$3" tag="$4"
  local out="$outroot/${tag}.out"
  run "$model" "$cfg" "$out"
  if ! tlc_launched "$out"; then
    echo "FAIL  $label (TLC did not launch)"
    tail -20 "$out"
    return 1
  fi
  if tlc_passed "$out"; then
    echo "PASS  $label  ($(states_line "$out"))"
    return 0
  fi
  echo "FAIL  $label (expected PASS, got violation)"
  tail -20 "$out"
  return 1
}

expect_fail() {
  local label="$1" model="$2" cfg="$3" expected="$4" tag="$5"
  local out="$outroot/${tag}.out"
  run "$model" "$cfg" "$out"
  if ! tlc_launched "$out"; then
    echo "FAIL  $label (TLC did not launch)"
    tail -20 "$out"
    return 1
  fi
  if tlc_deadlocked "$out"; then
    echo "FAIL  $label (expected $expected violation, got DEADLOCK)"
    tail -12 "$out"
    return 1
  fi
  if tlc_passed "$out"; then
    echo "FAIL  $label (expected $expected violation, model PASSED)"
    return 1
  fi
  if ! named_violation "$out" "$expected"; then
    echo "FAIL  $label (expected property $expected NOT the violation)"
    grep -m1 -E 'Invariant .+ is violated' "$out" || true
    tail -8 "$out"
    return 1
  fi
  echo "CEX   $label ($expected violated, as expected)  ($(states_line "$out"))"
  return 0
}

echo "=== E12-F AsyncRwLock formal gate (TLC2, workers=$WORKERS) ==="
echo
rc=0

# Freshness gate (fail-closed, PR #168 review closeout): the two generated
# negatives must be byte-identical to the current positive model's derivation.
# A stale negative would keep checking an outdated mutation while CI stays
# green, so this runs BEFORE any TLC execution.
for gen in gen-rwlock-neg-writer-revoke.py gen-rwlock-neg-deadline-precedence.py; do
  if ! python3 "$here/$gen" --check; then
    echo
    echo "=== gate failed: generated negative freshness ($gen) ==="
    exit 1
  fi
done

# Correct model: 13 invariants (RW1..RW10 + head-reconcile closure +
# reader non-revocation + resource-first deadline admission; audit #162
# MODEL-001/MODEL-002/MODEL-003 closure).
expect_pass "E12RwLock [13 invariants]" \
            E12RwLock E12RwLock.cfg E12RwLock.safety || rc=1

# Negative: reader bypasses writer
expect_fail "NEG ReaderBypass" \
            E12RwLockNegReaderBypass E12RwLockNegReaderBypass.cfg \
            NoReaderBarging E12RwLockNeg1 || rc=1
expect_fail "NEG NoReconcile (release strands grantable head)" \
            E12RwLockNegNoReconcile E12RwLockNegNoReconcile.cfg \
            InvNoStrandedGrantableHead E12RwLockNeg2 || rc=1
# Negative: cancel/expire writer-reconcile drops the activeReaders = 0 guard
# (generated from the positive model; freshness-checked above; see
# scripts/formal/gen-rwlock-neg-writer-revoke.py).
expect_fail "NEG WriterRevoke (reader revocation)" \
            E12RwLockNegWriterRevoke E12RwLockNegWriterRevoke.cfg \
            ReaderRevocationFree E12RwLockNeg3 || rc=1
# Negative: timed admission resolves Expired although the resource was
# admissible AND the evidence latches recorded it (deadline beats resource;
# the C++ precedence is the opposite). Mutates ONLY the outcome — the
# latches stay TRUE — so the invariant's failure proves property sensitivity
# (audit #162 MODEL-003 negative control; freshness-checked above).
expect_fail "NEG DeadlinePrecedence (due beats admissible)" \
            E12RwLockNegDeadlinePrecedence E12RwLockNegDeadlinePrecedence.cfg \
            InvResourceFirstDeadline E12RwLockNeg4 || rc=1

# Reachability witnesses (non-vacuity, audit #162 Phase 4): each NoReach*
# must be VIOLATED — the CEX trace is the witness that the reconcile branch
# is genuinely reachable in the as-built model.
expect_fail "REACH cancel reader-prefix merge" \
            E12RwLock E12RwLock.reach-cancel-merge.cfg \
            NoReachCancelReaderPrefixMerge E12RwLockReach1 || rc=1
expect_fail "REACH expire reader-prefix merge" \
            E12RwLock E12RwLock.reach-expire-merge.cfg \
            NoReachExpireReaderPrefixMerge E12RwLockReach2 || rc=1
expect_fail "REACH cancel writer-refused (R1)" \
            E12RwLock E12RwLock.reach-cancel-writer-refused.cfg \
            NoReachCancelWriterRefused E12RwLockReach3 || rc=1
expect_fail "REACH expire writer-refused (R2)" \
            E12RwLock E12RwLock.reach-expire-writer-refused.cfg \
            NoReachExpireWriterRefused E12RwLockReach4 || rc=1
expect_fail "REACH writer-blocked contrast" \
            E12RwLock E12RwLock.reach-writer-blocked.cfg \
            NoReachWriterBlockedByReaders E12RwLockReach5 || rc=1
# Timed-admission halves (audit #162 MODEL-003): precedence 1 fires with a
# genuinely due deadline (resource beats due), and precedence 2 (inline
# admission-expire) fires when the resource is not admissible.
expect_fail "REACH until resource-beat-due (MODEL-003)" \
            E12RwLock E12RwLock.reach-until-resource-beat-due.cfg \
            NoReachUntilResourceBeatDue E12RwLockReach6 || rc=1
expect_fail "REACH until admission-expire (MODEL-003)" \
            E12RwLock E12RwLock.reach-until-expired.cfg \
            NoReachUntilExpired E12RwLockReach7 || rc=1

echo
echo "=== gate ${rc}-ed (0 = all expected verdicts) ==="
exit "$rc"
