#!/usr/bin/env bash
# verify-e9-park-wake.sh — E9 park/wake protocol formal gate.
#
#   E9ParkWake (safety, split-wait)     -> all invariants PASS
#   E9ParkWake (liveness, split-wait)   -> liveness PASS
#   E9ParkWake (reference safety)       -> non-split E9 rule PASS (DIV-05)
#   E9ParkWakeWitnessRetire             -> NoReach* violated = causal witness
#                                         (#189 non-vacuity: RetireWorkerQuiescent
#                                         fires with the departure wake)
#   E9ParkWakeWitnessPnpExit            -> NoReachParticipantExitFired violated
#                                         (#191 non-vacuity: ParticipantNoProgressExit
#                                         fires with the departure wake)
#   E9ParkWakeWitnessPnpEndedRun        -> NoReachPnpExitEndedRun violated
#                                         (#191 non-vacuity: last-alive branch
#                                         classifies ReturnedStalled)
#   E9ParkWakeWitnessRefObservation     -> NoReachRefObservationPark violated
#                                         (#185 non-vacuity: an ENTRY-ARMED
#                                         reference park exists, so the faithful
#                                         `~SplitWait /\ observationArmed[w]`
#                                         escape is exercised)
#   E9ParkWakeWitnessRefUnbounded       -> NoReachUnboundedRefPark violated
#                                         (#185: an UN-ARMED reference park
#                                         exists -- the state the scoping of
#                                         InvLife1 must NOT claim always-leave)
#   E9ParkWakeWitnessRefDrainMWS3       -> NoReachRefDrainMWS3ArmedPark violated
#                                         (#185: the scoped InvLife1 antecedent
#                                         -- Drain+MW-S3 armed reference park --
#                                         is reachable, not vacuous)
#   E9ParkWakeWitnessStart1             -> NoReachStartW0First violated
#                                         (R-F1 non-vacuity, W-START-1: W0's
#                                         startup publication precedes W1's)
#   E9ParkWakeWitnessStart2             -> NoReachStartW1First violated
#                                         (R-F1 non-vacuity, W-START-2/3: W1
#                                         publishes before W0 -- the #223/#210
#                                         partial-population skew shape)
#   E9ParkWakeWitnessStartEstablished   -> NoReachPopulationEstablished violated
#                                         (R-F1 non-vacuity, W-START-4: the
#                                         steady-state population boundary is
#                                         reached from the startup Init)
#   E9ParkWakeWitnessStart5             -> NoReachStartW1IncumbentAfterSettlement
#                                         violated (R-F1 Corrective-1, W-START-5:
#                                         startup-history carry-over -- W1 stays
#                                         the incumbent participant after W0
#                                         later starts and the population
#                                         settles; a settled state the pre-R-F1
#                                         Init cannot generate, so post-
#                                         settlement guard coincidence is NOT
#                                         reachable-state refinement)
#   NegRetireDead                       -> NoReach* HOLD (witness fail-closed on the
#                                         exact pre-#189 contradictory action;
#                                         GENERATED by _gen_neg.py, #192)
#   NegParticipantDead                  -> NoReach* HOLD (witness fail-closed on the
#                                         exact pre-#191 double-prime contradiction;
#                                         GENERATED by _gen_neg.py, #191)
#   NegOldEscape                        -> InvNoCauselessReturn violated (fail-closed
#                                         on the pre-#185 always-escape `~SplitWait`:
#                                         an un-armed park returns with no wake due;
#                                         GENERATED, SplitWait=FALSE, #185)
#   NegNaiveEscape                      -> InvNoCauselessReturn violated (fail-closed
#                                         on the naive `ExternalWakePossible`
#                                         escape: a park armed at entry can be
#                                         entered when the flag has since cleared;
#                                         GENERATED, SplitWait=FALSE, #185)
#   BuggyDrainParks                     -> counterexample (liveness property violated)
#   BuggyMixedSource                    -> Inv7StateForm violated
#   BuggyPrePark                        -> Inv2NoLostWake / Inv4ExternalReadyWakes violated
#   BuggyNoBridge (Phase G)             -> Inv8BridgeReachesBackendPark violated
#                                         (model-level M1: bridge disabled;
#                                         GENERATED by _gen_neg.py, #192)
#   NegStartUnrefinedElection (R-F1)    -> InvStartupWellFormed violated
#                                         (naive #223 startup extension: the
#                                         Eligible authority keeps the
#                                         workerAlive-only shape; an unstarted
#                                         worker parks and takes the participant
#                                         slot; GENERATED, #223)
#   NegStartUnsettledTerminal (R-F1)    -> InvPopulationTerminal violated
#                                         (the join-boundary Settled gate dropped
#                                         from the run-ending classification: the
#                                         run returns with zero started workers;
#                                         GENERATED, #223)
#
# Freshness prerequisite (#192, #191, #185): NegRetireDead, BuggyNoBridge,
# NegParticipantDead, NegOldEscape, and NegNaiveEscape are full duplicated
# snapshots, so they are GENERATED
# from the current E9ParkWake.tla by _gen_neg.py and byte-compared (--check)
# BEFORE any TLC run. A stale, missing, or unexpected generated artifact
# fails the gate without starting TLC (a stale negative keeps checking an
# outdated mutation while CI stays green). BuggyDrainParks (EXTENDS-based)
# auto-tracks the positive model; BuggyPrePark/BuggyMixedSource are FROZEN
# pre-Phase-G historical controls (hand-written, intentionally NOT generated).
#
# Source-safe: TLC runs in an isolated mktemp workspace.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
spec="$repo/spec/tla/e9_park_wake"
workers="${TLC_WORKERS:-1}"

# Generated-negative freshness (#192): read-only --check; on failure TLC
# NEVER STARTS (fail-closed before any model checking).
if python3 "$spec/_gen_neg.py" --check; then
  echo "[freshness] PASS  (committed generated negatives match the current positive model + generator)"
else
  echo "[freshness] FAIL  (generated negatives are stale/missing/unexpected)"
  echo "=== gate failed: generated negative freshness (_gen_neg.py --check) ==="
  exit 1
fi

# Resolve jar via shared helper (sets TLA2TOOLS_JAR). Does NOT fall back to
# the repo-root jar, which is not checksum-verified; use bootstrap.py instead.
source "$here/resolve-jar.sh"
jar="$TLA2TOOLS_JAR"

if ! command -v java >/dev/null 2>&1; then
  echo "error: java not found on PATH" >&2; exit 2
fi

outroot="$(mktemp -d -t e9-pw.XXXXXX)"
cleanup() {
  if [[ -n "$outroot" ]] \
     && [[ "$outroot" == /tmp/e9-pw.* \
           || "$outroot" == "${TMPDIR:-/tmp}"/e9-pw.* ]]; then
    rm -rf -- "$outroot"
  fi
}
trap cleanup EXIT

workdir="$outroot/work"
mkdir -p "$workdir"
cp "$spec"/*.tla "$spec"/*.cfg "$workdir/"
cd "$workdir"

run_tlc() {
  local model="$1" cfg="$2" tag="$3"
  local metadir="$outroot/$tag.meta"
  mkdir -p "$metadir"
  java -XX:+UseParallelGC -cp "$jar" tlc2.TLC -nowarning \
       -workers "$workers" -metadir "$metadir" -config "$cfg" "$model" \
       >"$outroot/$tag.out" 2>&1 || true
}
launched() { grep -q '^Starting\.\.\.' "$1"; }
passed()   { grep -q 'Model checking completed. No error has been found' "$1"; }
named_violation() { grep -Eq "Invariant $2 is violated" "$1"; }

expect_pass() {
  local label="$1" model="$2" cfg="$3" tag="$4"
  local out="$outroot/$tag.out"
  run_tlc "$model" "$cfg" "$tag"
  if ! launched "$out"; then echo "FAIL  $label (no launch)"; tail -20 "$out"; return 1; fi
  if passed "$out"; then echo "PASS  $label"; return 0; fi
  echo "FAIL  $label (expected PASS)"; tail -20 "$out"; return 1
}

expect_fail() {
  local label="$1" model="$2" cfg="$3" expected="$4" tag="$5"
  local out="$outroot/$tag.out"
  run_tlc "$model" "$cfg" "$tag"
  if ! launched "$out"; then echo "FAIL  $label (no launch)"; tail -20 "$out"; return 1; fi
  if passed "$out"; then echo "FAIL  $label (expected $expected, PASSED)"; return 1; fi
  if ! named_violation "$out" "$expected"; then
    echo "FAIL  $label (expected $expected NOT the violation)"; tail -8 "$out"; return 1
  fi
  echo "CEX   $label ($expected violated)"; return 0
}

# BuggyDrainParks uses a liveness PROPERTY, not an INVARIANT.
expect_cex() {
  local label="$1" model="$2" cfg="$3" tag="$4"
  local out="$outroot/$tag.out"
  run_tlc "$model" "$cfg" "$tag"
  if ! launched "$out"; then echo "FAIL  $label (no launch)"; tail -20 "$out"; return 1; fi
  if passed "$out"; then echo "FAIL  $label (expected counterexample, PASSED)"; return 1; fi
  echo "CEX   $label (counterexample found)"; return 0
}

rc=0
echo "=== E9 Park/Wake formal gate (workers=$workers) ==="
expect_pass "E9ParkWake [safety, split-wait]" E9ParkWake E9ParkWake.cfg safety || rc=1
expect_pass "E9ParkWake [liveness, split-wait]" E9ParkWake E9ParkWakeLiveness.cfg liveness || rc=1
expect_pass "E9ParkWake [safety, reference]" E9ParkWake E9ParkWakeReference.cfg reference || rc=1
expect_pass "E9ParkWake [liveness, reference]" E9ParkWake E9ParkWakeReferenceLiveness.cfg ref_liveness || rc=1
# #189 non-vacuity witnesses: RetireWorkerQuiescent MUST fire, and the
# all-retired ReturnedQuiescent-at-quiescence chain MUST be reachable
# (NoReach* violated). Each witness in its own cfg so TLC checks both.
expect_fail "WitnessRetire (retire fires)" E9ParkWake \
  E9ParkWakeWitnessRetire.cfg NoReachRetireFired retire_witness || rc=1
expect_fail "WitnessTerminate (quiescent terminal chain)" E9ParkWake \
  E9ParkWakeWitnessTerminate.cfg NoReachQuiescentTerminate retire_terminate || rc=1
# #191 non-vacuity witnesses: ParticipantNoProgressExit MUST fire, and the
# last-alive branch MUST classify ReturnedStalled (NoReach* violated).
expect_fail "WitnessPnpExit (participant exit fires)" E9ParkWake \
  E9ParkWakeWitnessPnpExit.cfg NoReachParticipantExitFired pnp_exit_witness || rc=1
expect_fail "WitnessPnpEndedRun (last-alive ReturnedStalled)" E9ParkWake \
  E9ParkWakeWitnessPnpEndedRun.cfg NoReachPnpExitEndedRun pnp_ended_run_witness || rc=1
# #185 non-vacuity witnesses (reference config): the faithful escape and the
# scoped InvLife1 antecedent MUST be reachable, not vacuous truth.
expect_fail "WitnessRefObservation (armed reference park)" E9ParkWake \
  E9ParkWakeWitnessRefObservation.cfg NoReachRefObservationPark ref_obs_witness || rc=1
expect_fail "WitnessRefUnbounded (un-armed reference park)" E9ParkWake \
  E9ParkWakeWitnessRefUnbounded.cfg NoReachUnboundedRefPark ref_unbounded_witness || rc=1
expect_fail "WitnessRefDrainMWS3 (scoped InvLife1 antecedent)" E9ParkWake \
  E9ParkWakeWitnessRefDrainMWS3.cfg NoReachRefDrainMWS3ArmedPark ref_drain_witness || rc=1
# R-F1 non-vacuity witnesses (#223): the startup population states are
# genuinely represented — both publication orders, the partial population
# (#210 skew shape), and the steady-state population boundary.
expect_fail "WitnessStart1 (W0 publishes first)" E9ParkWake \
  E9ParkWakeWitnessStart1.cfg NoReachStartW0First start_w0_witness || rc=1
expect_fail "WitnessStart2 (W1 publishes first — #223 skew shape)" E9ParkWake \
  E9ParkWakeWitnessStart2.cfg NoReachStartW1First start_w1_witness || rc=1
expect_fail "WitnessStartEstablished (population boundary)" E9ParkWake \
  E9ParkWakeWitnessStartEstablished.cfg NoReachPopulationEstablished start_established_witness || rc=1
# R-F1 Corrective-1 non-vacuity witness (#223): startup history survives
# into a settled state -- the skew-elected W1 incumbent persists after W0
# publishes startup. History-sensitive settled state (LEGAL, no
# displacement obligation): NOT reachable in the pre-R-F1 model, which is
# exactly why transition-schema correspondence must not be claimed as
# reachable-state refinement.
expect_fail "WitnessStart5 (W1 incumbent survives settlement)" E9ParkWake \
  E9ParkWakeWitnessStart5.cfg NoReachStartW1IncumbentAfterSettlement start5_witness || rc=1
# #189 negative control: the exact pre-fix contradictory action keeps the
# retire dead, so the witness invariants HOLD -> the witness gate fails closed.
expect_pass "NegRetireDead (witness fail-closed)" E9ParkWakeNegRetireDead \
  E9ParkWakeNegRetireDead.cfg neg_retire_dead || rc=1
# #191 negative control: the exact pre-fix double-prime contradiction keeps
# ParticipantNoProgressExit dead, so the witness invariants HOLD -> the witness
# gate fails closed.
expect_pass "NegParticipantDead (witness fail-closed)" E9ParkWakeNegParticipantDead \
  E9ParkWakeNegParticipantDead.cfg neg_participant_dead || rc=1
# #185 negative controls (reference config, SplitWait=FALSE): both wrong
# escapes let an un-woken park return -- InvNoCauselessReturn must fire.
expect_fail "NegOldEscape (causeless-return fail-closed)" E9ParkWakeNegOldEscape \
  E9ParkWakeNegOldEscape.cfg InvNoCauselessReturn neg_old_escape || rc=1
expect_fail "NegNaiveEscape (causeless-return fail-closed)" E9ParkWakeNegNaiveEscape \
  E9ParkWakeNegNaiveEscape.cfg InvNoCauselessReturn neg_naive_escape || rc=1
expect_cex "BuggyDrainParks" E9ParkWakeBuggyDrainParks \
  E9ParkWakeBuggyDrainParks.cfg buggy_drain || rc=1
# R-F1 startup negative controls (#223, generated): the two naive-extension
# mutants are caught by the refined startup laws.
expect_fail "NegStartUnrefinedElection (unrefined eligibility)" E9ParkWakeNegStartUnrefinedElection \
  E9ParkWakeNegStartUnrefinedElection.cfg InvStartupWellFormed neg_start_election || rc=1
expect_fail "NegStartUnsettledTerminal (join boundary dropped)" E9ParkWakeNegStartUnsettledTerminal \
  E9ParkWakeNegStartUnsettledTerminal.cfg InvPopulationTerminal neg_start_terminal || rc=1
expect_fail "BuggyMixedSource" E9ParkWakeBuggyMixedSource \
  E9ParkWakeBuggyMixedSource.cfg Inv7StateForm buggy_mix || rc=1
expect_fail "BuggyPrePark" E9ParkWakeBuggyPrePark \
  E9ParkWakeBuggyPrePark.cfg Inv2NoLostWake buggy_prepark || rc=1
expect_fail "BuggyNoBridge" E9ParkWakeBuggyNoBridge \
  E9ParkWakeBuggyNoBridge.cfg Inv8BridgeReachesBackendPark buggy_nobridge || rc=1

echo
if [[ "$rc" -eq 0 ]]; then echo "=== PASS ==="; else echo "=== FAIL ==="; fi
exit "$rc"
