#!/usr/bin/env bash
# Verify the curated (named) seed generator is deterministic and matches the
# committed corpus byte-for-byte.
#
# Compiles fuzz/gen_seeds.cpp with plain clang++, runs it in a TEMPORARY empty
# directory, and compares only the curated NAMED seeds against the committed
# files under fuzz/corpus/<target>/. SHA-named libFuzzer-discovered seeds are
# NOT compared (the generator is not required to recreate them).
#
# Leaves the committed corpus untouched. Returns non-zero on drift (missing,
# extra, or byte-different curated seeds).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$PROJECT_ROOT"

if ! command -v clang++ >/dev/null 2>&1; then
    echo "ERROR: clang++ not found on PATH." >&2
    exit 1
fi

WORK="$(mktemp -d -t sluice-curated-verify.XXXXXX)"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT INT TERM

# Compile the generator into the temp dir.
GEN="${WORK}/gen_seeds"
clang++ -std=c++20 -O2 "${PROJECT_ROOT}/fuzz/gen_seeds.cpp" -o "$GEN"

# Run the generator inside the temp dir so it writes into temp/corpus/... rather
# than over the committed corpus. gen_seeds.cpp uses relative paths
# ("fuzz/corpus/<target>").
( cd "$WORK" && "$GEN" ) >/dev/null

# The curated named seeds per target. SHA-named (40 hex chars) seeds are excluded
# from this comparison: they are libFuzzer-discovered coverage seeds, not
# generated by gen_seeds.cpp.
declare -a TARGETS=(wal_read_record wal_roundtrip copy_all_fault)

MISSING=0
EXTRA=0
DIFF=0
CHECKED=0

for tgt in "${TARGETS[@]}"; do
    committed_dir="${PROJECT_ROOT}/fuzz/corpus/${tgt}"
    generated_dir="${WORK}/fuzz/corpus/${tgt}"

    # Build the set of curated (named, non-40-hex) committed seeds for this target.
    mapfile -t committed_named < <(
        git -C "$PROJECT_ROOT" ls-files -- "fuzz/corpus/${tgt}" \
            | xargs -n1 basename \
            | grep -v -E '^[0-9a-f]{40}$' \
            | sort -u
    )

    for name in "${committed_named[@]}"; do
        committed="${committed_dir}/${name}"
        generated="${generated_dir}/${name}"
        CHECKED=$((CHECKED + 1))
        if [[ ! -f "$generated" ]]; then
            echo "MISSING generated: ${tgt}/${name}"
            MISSING=$((MISSING + 1))
            continue
        fi
        if ! cmp -s "$committed" "$generated"; then
            echo "DIFF ${tgt}/${name}:"
            echo "  committed: $(wc -c <"$committed") bytes"
            echo "  generated: $(wc -c <"$generated") bytes"
            DIFF=$((DIFF + 1))
        fi
    done

    # Detect curated seeds the generator emits that are NOT committed (drift the
    # other way). Only consider named (non-40-hex) files.
    if [[ -d "$generated_dir" ]]; then
        while IFS= read -r gen_name; do
            if [[ "$gen_name" =~ ^[0-9a-f]{40}$ ]]; then continue; fi
            if [[ ! -f "${committed_dir}/${gen_name}" ]]; then
                echo "EXTRA generated (not committed): ${tgt}/${gen_name}"
                EXTRA=$((EXTRA + 1))
            fi
        done < <(cd "$generated_dir" && ls -1)
    fi
done

echo ""
echo "Curated seed verification: checked=${CHECKED} missing=${MISSING} extra=${EXTRA} diff=${DIFF}"

if [[ $MISSING -gt 0 || $EXTRA -gt 0 || $DIFF -gt 0 ]]; then
    echo "VERDICT: FAIL (curated seed drift detected)"
    exit 1
fi
echo "VERDICT: PASS (curated named seeds are deterministic and match the committed corpus)"
